const VIDEO_REQUEST_DIFF = 15;//secs
const NONE_USERNAME_VIDEO_REQUEST_DIFF = 20;//secs

const VIDEO_REQUEST_DETECTION_MAX_DURATION = 20;//secs
const MAX_TIME_COPYRIGHTWARNING_ALLOW = 1;//times
const USER_ACTIVE = 1;//times
const USER_SUSPENDED = 0;//times
const TIME_BETWEEN_WARNINGS = 1000 * 30; //miliseconds
const MAX_WARNINGS_ALLOWED = 3//times
const INTERNAL_TOKEN = 'xfA6cYCYqhP4vjgUV2zU1abUwV1WjjTEvD1IzgqBRgabEX0AUfSzuFHlKIvLTpXEJFjAs7';
module.exports = {
    VIDEO_REQUEST_DIFF,
    VIDEO_REQUEST_DETECTION_MAX_DURATION,
    MAX_TIME_COPYRIGHTWARNING_ALLOW,
    USER_ACTIVE,
    USER_SUSPENDED,
    TIME_BETWEEN_WARNINGS,
    MAX_WARNINGS_ALLOWED,
    INTERNAL_TOKEN,
    NONE_USERNAME_VIDEO_REQUEST_DIFF,
}